fix cuda target name
desul/desul pull request #116
Opened 2023-10-27 22:53 UTC by trws

This is one of the dumber mistakes I've made in a while, messed up the blt target name for an updated one that doesn't work yet. This fixes it.

2023-10-28 02:40 UTC, dalg24 requested changes
This is a partially undoing #115

Please elaborate why we should not be using the qualified target and why the HIP one does not need the same fix.

2023-10-28 17:59 UTC, trws commented
Of course, the cause is that the qualified target doesn’t work for Cuda yet.  I could add an alias to hide the issue until the blt update comes down, or leave it like this.  The hip one, ironically, is both already there and the original bare hip name was removed, hence my confusion and this whole mess.

2023-10-28 18:40 UTC, dalg24 commented
What about something like
```cmake
# FIXME_BLT
if(TARGET cuda AND NOT TARGET blt::cuda)
  add_library(blt::cuda ALIAS cuda)
endif()

2023-10-30 18:08 UTC, dalg24 approved these changes

2023-10-30 18:23 UTC, masterleinad approved these changes

2023-10-30 18:37 UTC, merged