Adding ScopeCaller for "non-atomic" atomics
desul/desul pull request #50
Opened 2022-01-19 18:26 UTC by crtrott

2022-01-19 18:29 UTC, crtrott commented
@trws this is the non-atomic fallback option for apps building in MPI only mode. I called the scope "CallerScope" instead of "ThreadScope" since thread is somewhat overloaded. For example you could be calling this from something like a vector lane or "CUDA Thread". 

Generally I think the CallerScope could be useful in writing generic functions. For example you may have a function which modifies an input, where there is no conflict stuff going on in the function itself but maybe the calling scope of the function may sometimes call the function in a way where multiple threads will try to modify the same input, and sometimes so that each thread has its own input array. Templating on the scope would allow this to work.

2022-01-19 19:01 UTC, dalg24 requested changes
I only have comments on the form and the scope of the PR.

The changes related to the new memory scope are fine by me.

2022-01-19 20:41 UTC, crtrott commented on atomics/include/desul/atomics/Compare_Exchange_GCC.hpp
> +    Impl::dont_deduce_this_parameter_t<T> value,
yes it does because I need it in conjunction with the new overloads for correct prioritization

2022-01-19 20:46 UTC, crtrott commented on atomics/include/desul/atomics/Compare_Exchange_GCC.hpp
> +    Impl::dont_deduce_this_parameter_t<T> value,
(i.e. the new versions only are seen as more special if they treat parameter deduction the same.

2022-01-25 19:13 UTC, crtrott commented
@trws Hey can we get a thumbs-up/down for the general design and the naming?

2022-01-25 22:38 UTC, trws commented
The implementation looks fine, though @dalg24 makes some good points.  Naming probably works, we had talked about something like sequential or serial, but "encountering thread" or "calling context" are sufficiently established that I would expect this to make sense to people. :+1:

2022-01-25 22:41 UTC, crtrott commented
Yeah regarding Damiens points I will rebase this stuff on top of the other PR later.

2022-03-23 20:20 UTC, crtrott commented
Superceded by #60

2022-03-23 20:20 UTC, closed without merging