Make building tests optional
desul/desul pull request #87
Opened 2023-01-13 22:08 UTC by masterleinad

Currently, it's not possible to configure `desul` without configuring tests (which requires `Kokkos`) although there is a `CMake` option that should control it.

2023-01-13 22:15 UTC, dalg24 commented on atomics/CMakeLists.txt
> +if(BUILD_TESTING)
Please discuss the choice for the option to enable testing

2023-01-13 22:17 UTC, dalg24 commented on atomics/CMakeLists.txt
> +if(BUILD_TESTING)
The CTest module defines a `BUILD_TESTING` but it is not obvious to me where the `include(CTest)` would occur.

2023-01-13 22:20 UTC, dalg24 commented on atomics/CMakeLists.txt
> +if(BUILD_TESTING)
Considering https://github.com/LLNL/blt/blob/8c229991e65e7a9603c621b47cb3ba158bb7468c/cmake/BLTOptions.cmake#L16 and the other options we currently accept, is `ENABLE_TESTS` a better choice?

2023-01-14 03:09 UTC, dalg24 commented on atomics/CMakeLists.txt
> +if(BUILD_TESTING)
And there is `DESUL_ENABLE_TESTS` as well  
https://github.com/desul/desul/blob/f63c5ee63a2f3aababaad995561d15b2b4951611/CMakeLists.txt#L14
https://github.com/desul/desul/blob/f63c5ee63a2f3aababaad995561d15b2b4951611/atomics/unit_tests/kokkos_based/CMakeLists.txt#L1

2023-01-14 03:11 UTC, dalg24 requested changes
> Currently, it's not possible to configure desul without configuring tests (which requires Kokkos) although there is a CMake option that should control it.

Not true.  You can configure with `-DENABLE_TESTS=OFF` or even `-DDESUL_ENABLE_TESTS=OFF`

2023-01-14 03:17 UTC, masterleinad commented
> Not true. You can configure with `-DENABLE_TESTS=OFF` or even `-DDESUL_ENABLE_TESTS=OFF`

Ah, my bad, you're right. I was looking in the wrong place to find the right options. It might still be sensible to have testing off by default to not be forced to find a Kokkos installation by default.

2023-01-14 03:17 UTC, closed without merging