Replace HIP_LOCK_ARRAYS macros by functions
desul/desul pull request #88
Opened 2023-01-17 22:02 UTC by masterleinad

Corresponding to https://github.com/kokkos/kokkos/pull/5770. Analogous to https://github.com/desul/desul/pull/64.

2023-01-18 14:41 UTC, trws commented
Looks good to me pending checks that the RDC/non-RDC issue doesn’t come back.

2023-01-18 15:51 UTC, masterleinad commented
> Looks good to me pending checks that the RDC/non-RDC issue doesn’t come back.

The LAMMPS test that failed previously with CUDA appears to run fine with this change.

2023-01-19 22:38 UTC, dalg24 submitted a review, later dismissed
LGTM but I would like a review from @Rombur

2023-01-20 15:12 UTC, masterleinad commented
> The tests are not passing

Yeah, the update in the `fedora` CI containers broke it. Since the fix is only in `develop`, I decided to use that for testing now. Instead, we could also continue to test with `Kokkos` 3.4.01` and disable the `fedora:rawhide` tests.

2023-01-20 15:46 UTC, Rombur submitted a review, later dismissed

2023-01-20 16:24 UTC, dalg24 requested changes

2023-01-20 16:24 UTC, dalg24 commented on .github/workflows/continuous-integration-workflow.yml
> +          git clone --branch develop --single-branch --depth 1 https://github.com/kokkos/kokkos.git kokkos_src
Pin the version.

2023-01-20 20:22 UTC, dalg24 requested changes
Open another pull request where you bump the Kokkos requirements and update the CI.
Make sure you also update https://github.com/desul/desul/blob/f63c5ee63a2f3aababaad995561d15b2b4951611/atomics/performance_tests/kokkos_based/CMakeLists.txt#L2

2023-01-20 21:24 UTC, masterleinad commented
> Open another pull request where you bump the Kokkos requirements and update the CI.

See #90.

2023-01-20 22:19 UTC, dalg24 commented
Will need to re-run tests after #92 is merged

2023-01-22 02:32 UTC, dalg24 submitted a review, later dismissed

2023-01-22 20:00 UTC, dalg24 approved these changes

2023-01-23 16:45 UTC, Rombur approved these changes

2023-01-23 16:50 UTC, merged